cmake_minimum_required(VERSION 3.20)
file(REMOVE_RECURSE "${WORK_DIR}")
file(MAKE_DIRECTORY "${WORK_DIR}/tree/b-sub")
set(root "${WORK_DIR}/tree")
file(WRITE "${root}/z.bin" "abc")
file(WRITE "${root}/b-sub/c.bin" "xabc")
file(WRITE "${root}/a.bin" "abcabc")
set(options -r)
set(query "abc")
set(paths "${root}")
set(expected_code 0)
set(expect_error FALSE)
set(expected "${root}/a.bin:0x0000000000000000:raw\n${root}/a.bin:0x0000000000000003:raw\n${root}/b-sub/c.bin:0x0000000000000001:raw\n${root}/z.bin:0x0000000000000000:raw\n")

if(CASE STREQUAL "nested")
elseif(CASE STREQUAL "long_option")
    set(options --recursive)
elseif(CASE STREQUAL "single_file")
    set(paths "${root}/z.bin")
    set(expected "${paths}:0x0000000000000000:raw\n")
elseif(CASE STREQUAL "no_match")
    set(query "absent")
    set(expected_code 1)
    set(expected "")
elseif(CASE STREQUAL "empty")
    set(paths "${WORK_DIR}/empty")
    file(MAKE_DIRECTORY "${paths}")
    set(expected_code 1)
    set(expected "")
elseif(CASE STREQUAL "hidden")
    file(MAKE_DIRECTORY "${root}/.git" "${root}/build")
    file(WRITE "${root}/.git/hidden.bin" "abc")
    file(WRITE "${root}/.hidden" "abc")
    file(WRITE "${root}/build/generated.bin" "abc")
    set(expected "${root}/.git/hidden.bin:0x0000000000000000:raw\n${root}/.hidden:0x0000000000000000:raw\n${root}/a.bin:0x0000000000000000:raw\n${root}/a.bin:0x0000000000000003:raw\n${root}/b-sub/c.bin:0x0000000000000001:raw\n${root}/build/generated.bin:0x0000000000000000:raw\n${root}/z.bin:0x0000000000000000:raw\n")
elseif(CASE STREQUAL "mixed_paths")
    file(WRITE "${WORK_DIR}/first.bin" "abc")
    set(paths "${WORK_DIR}/first.bin" "${root}" "${root}/z.bin")
    set(expected "${WORK_DIR}/first.bin:0x0000000000000000:raw\n${expected}${root}/z.bin:0x0000000000000000:raw\n")
elseif(CASE STREQUAL "error_precedence")
    set(paths "${WORK_DIR}/missing" "${root}" "${WORK_DIR}/missing-too" "${root}/z.bin")
    string(APPEND expected "${root}/z.bin:0x0000000000000000:raw\n")
    set(expected_code 2)
    set(expect_error TRUE)
elseif(CASE STREQUAL "hex")
    set(options --hex -r)
    set(query "00 ff 00")
    configure_file("${SOURCE_DIR}/fixtures/binary.bin" "${root}/b-sub/binary.bin" COPYONLY)
    set(expected "${root}/b-sub/binary.bin:0x0000000000000000:raw\n${root}/b-sub/binary.bin:0x0000000000000002:raw\n")
elseif(CASE STREQUAL "chunk_boundary")
    string(REPEAT "x" 65534 prefix)
    file(WRITE "${root}/b-sub/c.bin" "${prefix}abc")
    string(REPLACE "0000000000000001" "000000000000fffe" expected "${expected}")
elseif(CASE STREQUAL "trailing_separator")
    set(paths "${root}/")
elseif(CASE STREQUAL "dot")
    set(paths ".")
    string(REPLACE "${root}" "." expected "${expected}")
elseif(CASE STREQUAL "parent")
    set(paths "..")
    string(REPLACE "${root}" ".." expected "${expected}")
elseif(CASE STREQUAL "dash_query")
    set(options -r --)
    set(query "-abc")
    file(WRITE "${root}/z.bin" "-abc")
    set(expected "${root}/z.bin:0x0000000000000000:raw\n")
elseif(CASE STREQUAL "duplicate_option")
    set(options -r --recursive)
    set(expected "")
    set(expected_code 2)
    set(expect_error TRUE)
elseif(CASE STREQUAL "links" OR CASE STREQUAL "explicit_dir_link" OR
       CASE STREQUAL "explicit_file_link" OR CASE STREQUAL "dangling_link")
    file(CREATE_LINK "${root}" "${root}/b-sub/loop" SYMBOLIC RESULT link_result)
    if(NOT "${link_result}" STREQUAL "0")
        message("SKIP: symbolic link creation is unavailable: ${link_result}")
        return()
    endif()
    file(CREATE_LINK "${root}/z.bin" "${WORK_DIR}/file-link" SYMBOLIC RESULT link_result)
    if(NOT "${link_result}" STREQUAL "0")
        message(FATAL_ERROR "File symlink creation failed: ${link_result}")
    endif()
    file(CREATE_LINK "${root}" "${WORK_DIR}/dir-link" SYMBOLIC RESULT link_result)
    if(NOT "${link_result}" STREQUAL "0")
        message(FATAL_ERROR "Directory symlink creation failed: ${link_result}")
    endif()
    file(CREATE_LINK "${root}/z.bin" "${root}/file-link" SYMBOLIC RESULT link_result)
    if(NOT "${link_result}" STREQUAL "0")
        message(FATAL_ERROR "Discovered file symlink creation failed: ${link_result}")
    endif()
    file(CREATE_LINK "${root}/absent" "${root}/broken-link" SYMBOLIC RESULT link_result)
    if(NOT "${link_result}" STREQUAL "0")
        message(FATAL_ERROR "Dangling symlink creation failed: ${link_result}")
    endif()
    if(CASE STREQUAL "explicit_dir_link")
        set(paths "${WORK_DIR}/dir-link")
        string(REPLACE "${root}" "${paths}" expected "${expected}")
    elseif(CASE STREQUAL "explicit_file_link")
        set(paths "${WORK_DIR}/file-link")
        set(expected "${paths}:0x0000000000000000:raw\n")
    elseif(CASE STREQUAL "dangling_link")
        set(paths "${root}/broken-link" "${root}")
        set(expected_code 2)
        set(expect_error TRUE)
    endif()
else()
    message(FATAL_ERROR "Unknown recursive CLI test: ${CASE}")
endif()

set(working_directory "${root}")
if(CASE STREQUAL "parent")
    set(working_directory "${root}/b-sub")
endif()
execute_process(COMMAND "${PROGRAM}" ${options} "${query}" ${paths}
    WORKING_DIRECTORY "${working_directory}"
    RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 15)
string(REPLACE "\r\n" "\n" output "${output}")
if(NOT "${code}" STREQUAL "${expected_code}")
    message(FATAL_ERROR "${CASE}: exit ${code}, expected ${expected_code}; stderr: ${error}")
endif()
if(NOT "${output}" STREQUAL "${expected}")
    message(FATAL_ERROR "${CASE}: stdout:\n${output}\nExpected:\n${expected}")
endif()
if(expect_error)
    if("${error}" STREQUAL "")
        message(FATAL_ERROR "${CASE}: missing error diagnostic")
    endif()
elseif(NOT "${error}" STREQUAL "")
    message(FATAL_ERROR "${CASE}: unexpected stderr: ${error}")
endif()
