cmake_minimum_required(VERSION 3.20)
file(MAKE_DIRECTORY "${WORK_DIR}")
set(input "${WORK_DIR}/input file.bin")
file(WRITE "${input}" "abc--abc-ABC")
set(query "abc")
set(options)
set(paths "${input}")
set(expected_code 0)
set(expected_output "${input}:0x0000000000000000:raw\n${input}:0x0000000000000005:raw\n")
set(expect_error FALSE)

if(CASE STREQUAL "match")
elseif(CASE STREQUAL "no_match")
    set(query "xyz")
    set(expected_code 1)
    set(expected_output "")
elseif(CASE STREQUAL "missing_file")
    set(paths "${WORK_DIR}/missing.bin")
    set(expected_code 2)
    set(expected_output "")
    set(expect_error TRUE)
elseif(CASE STREQUAL "empty_query")
    set(query "")
    set(expected_code 2)
    set(expected_output "")
    set(expect_error TRUE)
elseif(CASE STREQUAL "no_arguments" OR CASE STREQUAL "missing_path")
    set(expected_code 2)
    set(expected_output "")
    set(expect_error TRUE)
elseif(CASE STREQUAL "unknown_option")
    set(options --bogus)
    set(expected_code 2)
    set(expected_output "")
    set(expect_error TRUE)
elseif(CASE STREQUAL "hex")
    set(options --hex)
    set(query "61 62 63")
elseif(CASE STREQUAL "hex_binary")
    set(options --hex)
    set(query "00 fF 00")
    set(paths "${SOURCE_DIR}/fixtures/binary.bin")
    set(expected_output "${paths}:0x0000000000000000:raw\n${paths}:0x0000000000000002:raw\n")
elseif(CASE STREQUAL "hex_odd" OR CASE STREQUAL "hex_invalid" OR CASE STREQUAL "hex_empty")
    set(options --hex)
    if(CASE STREQUAL "hex_odd")
        set(query "abc")
    elseif(CASE STREQUAL "hex_invalid")
        set(query "00 GG")
    else()
        set(query "   ")
    endif()
    set(expected_code 2)
    set(expected_output "")
    set(expect_error TRUE)
elseif(CASE STREQUAL "multiple_files")
    set(other "${WORK_DIR}/other.bin")
    file(WRITE "${other}" "xabc")
    list(APPEND paths "${other}")
    string(APPEND expected_output "${other}:0x0000000000000001:raw\n")
elseif(CASE STREQUAL "error_precedence")
    set(paths "${WORK_DIR}/missing.bin" "${input}")
    set(expected_code 2)
    set(expect_error TRUE)
elseif(CASE STREQUAL "dash_query")
    set(options --)
    set(query "-abc")
    file(WRITE "${input}" "x-abc")
    set(expected_output "${input}:0x0000000000000001:raw\n")
elseif(CASE STREQUAL "directory")
    set(paths "${WORK_DIR}")
    set(expected_code 2)
    set(expected_output "")
    set(expect_error TRUE)
elseif(CASE STREQUAL "literal_backslash")
    set(query "\\x61")
    file(WRITE "${input}" "a--\\x61")
    set(expected_output "${input}:0x0000000000000003:raw\n")
elseif(CASE STREQUAL "chunk_boundary")
    string(REPEAT "x" 65534 prefix)
    file(WRITE "${input}" "${prefix}abc")
    set(expected_output "${input}:0x000000000000fffe:raw\n")
elseif(CASE STREQUAL "chunk_overlap")
    string(REPEAT "x" 65535 prefix)
    file(WRITE "${input}" "${prefix}aaaa")
    set(query "aaa")
    set(expected_output "${input}:0x000000000000ffff:raw\n${input}:0x0000000000010000:raw\n")
elseif(CASE STREQUAL "empty_file" OR CASE STREQUAL "short_file")
    if(CASE STREQUAL "empty_file")
        file(WRITE "${input}" "")
    else()
        file(WRITE "${input}" "ab")
    endif()
    set(expected_code 1)
    set(expected_output "")
else()
    message(FATAL_ERROR "Unknown CLI test: ${CASE}")
endif()

if(CASE STREQUAL "no_arguments")
    execute_process(COMMAND "${PROGRAM}" RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE error)
elseif(CASE STREQUAL "missing_path")
    execute_process(COMMAND "${PROGRAM}" "abc" RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE error)
else()
    execute_process(COMMAND "${PROGRAM}" ${options} "${query}" ${paths}
        RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE error)
endif()
string(REPLACE "\r\n" "\n" output "${output}")
if(NOT "${code}" STREQUAL "${expected_code}")
    message(FATAL_ERROR "${CASE}: exit ${code}, expected ${expected_code}; stderr: ${error}")
endif()
if(NOT "${output}" STREQUAL "${expected_output}")
    message(FATAL_ERROR "${CASE}: unexpected stdout:\n${output}\nExpected:\n${expected_output}")
endif()
if(expect_error)
    if("${error}" STREQUAL "")
        message(FATAL_ERROR "${CASE}: expected an error diagnostic")
    endif()
elseif(NOT "${error}" STREQUAL "")
    message(FATAL_ERROR "${CASE}: unexpected stderr: ${error}")
endif()
