cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED PROGRAM OR NOT DEFINED CASE OR NOT DEFINED WORK_DIR OR NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "Missing test arguments")
endif()
file(REMOVE_RECURSE "${WORK_DIR}")
file(MAKE_DIRECTORY "${WORK_DIR}")
file(COPY "${SOURCE_DIR}/fixtures/text-mixed.bin" DESTINATION "${WORK_DIR}")
set(raw "text-mixed.bin:0x0000000000000000:raw\n")
set(utf8 "text-mixed.bin:0x0000000000000000:utf8\n")
set(le "text-mixed.bin:0x0000000000000008:utf16-le\n")
set(be "text-mixed.bin:0x0000000000000010:utf16-be\n")
set(args --text abc text-mixed.bin)
set(expected "${utf8}${le}${be}")
set(code 0)
set(error "")
if(CASE STREQUAL "bundle")
elseif(CASE STREQUAL "utf8")
    set(args --morph utf8 abc text-mixed.bin)
    set(expected "${utf8}")
elseif(CASE STREQUAL "le")
    set(args --morph utf16-le abc text-mixed.bin)
    set(expected "${le}")
elseif(CASE STREQUAL "be")
    set(args --morph utf16-be abc text-mixed.bin)
    set(expected "${be}")
elseif(CASE STREQUAL "subset_order")
    set(args --morph utf16-be --morph utf16-le abc text-mixed.bin)
    set(expected "${le}${be}")
elseif(CASE STREQUAL "raw_utf8")
    set(args --morph utf8 --morph raw abc text-mixed.bin)
    set(expected "${raw}${utf8}")
elseif(CASE STREQUAL "raw")
    set(args --morph raw abc text-mixed.bin)
    set(expected "${raw}")
elseif(CASE STREQUAL "default_raw")
    set(args abc text-mixed.bin)
    set(expected "${raw}")
elseif(CASE STREQUAL "text_hex")
    set(args --text --hex 616263 text-mixed.bin)
    set(code 2)
elseif(CASE STREQUAL "hex_text")
    set(args --hex --text 616263 text-mixed.bin)
    set(code 2)
elseif(CASE STREQUAL "morph_hex")
    set(args --morph raw --hex 616263 text-mixed.bin)
    set(code 2)
elseif(CASE STREQUAL "hex_morph")
    set(args --hex --morph raw 616263 text-mixed.bin)
    set(code 2)
elseif(CASE STREQUAL "text_morph")
    set(args --text --morph utf8 abc text-mixed.bin)
    set(code 2)
elseif(CASE STREQUAL "morph_text")
    set(args --morph utf8 --text abc text-mixed.bin)
    set(code 2)
elseif(CASE STREQUAL "duplicate_text")
    set(args --text --text abc text-mixed.bin)
    set(code 2)
elseif(CASE STREQUAL "duplicate_morph")
    set(args --morph utf8 --morph utf8 abc text-mixed.bin)
    set(code 2)
    set(error "unsupported or repeated morph")
elseif(CASE STREQUAL "missing_morph")
    set(args --morph)
    set(code 2)
    set(error "requires a name")
elseif(CASE STREQUAL "unsupported_morph")
    set(args --morph base64-decoded abc text-mixed.bin)
    set(code 2)
    set(error "unsupported or repeated morph")
elseif(CASE STREQUAL "empty_text")
    # execute_process receives quoted literal arguments: CMake list expansion
    # would discard the empty query being tested.
    execute_process(COMMAND "${PROGRAM}" --text "" text-mixed.bin
        WORKING_DIRECTORY "${WORK_DIR}" RESULT_VARIABLE actual
        OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT actual EQUAL 2 OR NOT out STREQUAL "" OR NOT err MATCHES "empty query")
        message(FATAL_ERROR "Empty text query not rejected: ${actual} ${out} ${err}")
    endif()
    return()
elseif(CASE STREQUAL "no_match")
    set(args --text xyz text-mixed.bin)
    set(code 1)
elseif(CASE STREQUAL "case_sensitive")
    set(args --text ABC text-mixed.bin)
    set(code 1)
elseif(CASE STREQUAL "recursive")
    file(MAKE_DIRECTORY "${WORK_DIR}/tree/nested")
    file(COPY "${SOURCE_DIR}/fixtures/text-mixed.bin" DESTINATION "${WORK_DIR}/tree/nested")
    set(args -r --text abc tree)
    string(REPLACE "text-mixed.bin:" "tree/nested/text-mixed.bin:" expected "${expected}")
elseif(CASE STREQUAL "error_precedence")
    set(args --text abc missing.bin text-mixed.bin)
    set(code 2)
    set(error "missing.bin")
elseif(CASE STREQUAL "missing_path")
    set(args --text abc)
    set(code 2)
    set(error "at least one path")
elseif(CASE STREQUAL "dash_query")
    file(WRITE "${WORK_DIR}/dash.bin" "--abc")
    set(args --text -- --abc dash.bin)
    set(expected "dash.bin:0x0000000000000000:utf8\n")
elseif(CASE STREQUAL "odd_offset")
    # One byte precedes the UTF-16LE form; no even-offset restriction.
    file(COPY "${SOURCE_DIR}/fixtures/text-odd.bin" DESTINATION "${WORK_DIR}")
    set(args --morph utf16-le abc text-odd.bin)
    set(expected "text-odd.bin:0x0000000000000001:utf16-le\n")
elseif(CASE STREQUAL "truncated_wide")
    file(COPY "${SOURCE_DIR}/fixtures/text-truncated.bin" DESTINATION "${WORK_DIR}")
    set(args --morph utf16-le abc text-truncated.bin)
    set(code 1)
elseif(CASE STREQUAL "no_terminator")
    file(COPY "${SOURCE_DIR}/fixtures/text-le.bin" DESTINATION "${WORK_DIR}")
    set(args --morph utf16-le abc text-le.bin)
    set(expected "text-le.bin:0x0000000000000000:utf16-le\n")
elseif(CASE STREQUAL "unicode")
    file(READ "${SOURCE_DIR}/fixtures/text-query.utf8" query)
    file(COPY "${SOURCE_DIR}/fixtures/text-unicode.bin" DESTINATION "${WORK_DIR}")
    set(args --text "${query}" text-unicode.bin)
    set(expected "text-unicode.bin:0x0000000000000000:utf8\ntext-unicode.bin:0x0000000000000010:utf16-le\ntext-unicode.bin:0x0000000000000020:utf16-be\n")
else()
    message(FATAL_ERROR "Unknown case: ${CASE}")
endif()
if(code EQUAL 1)
    set(expected "")
elseif(code EQUAL 2 AND NOT CASE STREQUAL "error_precedence")
    set(expected "")
endif()
execute_process(COMMAND "${PROGRAM}" ${args}
    WORKING_DIRECTORY "${WORK_DIR}" RESULT_VARIABLE actual
    OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
string(REPLACE "\r\n" "\n" out "${out}")
if(NOT "${actual}" STREQUAL "${code}" OR NOT "${out}" STREQUAL "${expected}")
    message(FATAL_ERROR "${CASE}: code=${actual} expected=${code}\nout=${out}\nexpected=${expected}\nerr=${err}")
endif()
if(code EQUAL 2)
    if(err STREQUAL "" OR (NOT error STREQUAL "" AND NOT err MATCHES "${error}"))
        message(FATAL_ERROR "Missing expected diagnostic '${error}': ${err}")
    endif()
elseif(NOT err STREQUAL "")
    message(FATAL_ERROR "Unexpected diagnostic: ${err}")
endif()
